// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clusters_admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countNodesInCluster = `-- name: CountNodesInCluster :one

SELECT count(*) FROM nodes WHERE cluster_id = $1
`

// Cluster 删除（DELETE /api/clusters/{id}）查询。
// 软删除策略：有节点时端点层拒绝（409）；0005 起删除 = 打 deleted_at（name
// 唯一性是存活行部分索引，原名自动可复用，不再需要改名把戏）。
func (q *Queries) CountNodesInCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNodesInCluster, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeleteCluster = `-- name: SoftDeleteCluster :execrows
UPDATE clusters SET deleted_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteCluster(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteCluster, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
