// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clusters.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addMembership = `-- name: AddMembership :exec
INSERT INTO cluster_members (cluster_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddMembershipParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddMembership(ctx context.Context, arg AddMembershipParams) error {
	_, err := q.db.Exec(ctx, addMembership, arg.ClusterID, arg.UserID, arg.Role)
	return err
}

const countOwnedLiveClusters = `-- name: CountOwnedLiveClusters :one
SELECT count(*) FROM clusters c
JOIN cluster_members m ON m.cluster_id = c.id
WHERE m.user_id = $1 AND m.role = 'owner' AND c.deleted_at IS NULL
`

// 自助建 cluster 的每用户限额判定（只数存活且任 owner 的 cluster）。
func (q *Queries) CountOwnedLiveClusters(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOwnedLiveClusters, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCluster = `-- name: CreateCluster :one
INSERT INTO clusters (id, name, owner_id, personal) VALUES ($1, $2, $3, $4) RETURNING id, name, owner_id, created_at, deleted_at, personal
`

type CreateClusterParams struct {
	ID       uuid.UUID `json:"id"`
	Name     string    `json:"name"`
	OwnerID  uuid.UUID `json:"owner_id"`
	Personal bool      `json:"personal"`
}

func (q *Queries) CreateCluster(ctx context.Context, arg CreateClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, createCluster,
		arg.ID,
		arg.Name,
		arg.OwnerID,
		arg.Personal,
	)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Personal,
	)
	return i, err
}

const getClusterByID = `-- name: GetClusterByID :one
SELECT id, name, owner_id, created_at, deleted_at, personal FROM clusters WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClusterByID(ctx context.Context, id uuid.UUID) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByID, id)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Personal,
	)
	return i, err
}

const getClusterByName = `-- name: GetClusterByName :one
SELECT id, name, owner_id, created_at, deleted_at, personal FROM clusters WHERE name = $1 AND deleted_at IS NULL
`

func (q *Queries) GetClusterByName(ctx context.Context, name string) (Cluster, error) {
	row := q.db.QueryRow(ctx, getClusterByName, name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Personal,
	)
	return i, err
}

const listClustersForUser = `-- name: ListClustersForUser :many
SELECT c.id, c.name, c.owner_id, c.created_at, c.personal, m.role,
       (SELECT count(*) FROM cluster_members cm
         WHERE cm.cluster_id = c.id) AS member_count,
       (SELECT count(*) FROM nodes n WHERE n.cluster_id = c.id) AS node_count
FROM clusters c JOIN cluster_members m ON m.cluster_id = c.id
WHERE m.user_id = $1 AND c.deleted_at IS NULL ORDER BY c.name
`

type ListClustersForUserRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	OwnerID     uuid.UUID `json:"owner_id"`
	CreatedAt   time.Time `json:"created_at"`
	Personal    bool      `json:"personal"`
	Role        string    `json:"role"`
	MemberCount int64     `json:"member_count"`
	NodeCount   int64     `json:"node_count"`
}

// deleted_at IS NULL：软删除的 cluster 不再出现在用户列表（0005 存量缺陷修复）。
// member/node 计数随行带出（子查询聚合，Web 列表页一次拉齐免 N+1）。
func (q *Queries) ListClustersForUser(ctx context.Context, userID uuid.UUID) ([]ListClustersForUserRow, error) {
	rows, err := q.db.Query(ctx, listClustersForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClustersForUserRow
	for rows.Next() {
		var i ListClustersForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.OwnerID,
			&i.CreatedAt,
			&i.Personal,
			&i.Role,
			&i.MemberCount,
			&i.NodeCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameCluster = `-- name: RenameCluster :one
UPDATE clusters SET name = $2 WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, owner_id, created_at, deleted_at, personal
`

type RenameClusterParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) RenameCluster(ctx context.Context, arg RenameClusterParams) (Cluster, error) {
	row := q.db.QueryRow(ctx, renameCluster, arg.ID, arg.Name)
	var i Cluster
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.Personal,
	)
	return i, err
}
