// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :exec
INSERT INTO cluster_members (cluster_id, user_id, role) VALUES ($1, $2, $3)
`

type AddMemberParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.ClusterID, arg.UserID, arg.Role)
	return err
}

const countClusterOwners = `-- name: CountClusterOwners :one
SELECT count(*) FROM cluster_members WHERE cluster_id = $1 AND role = 'owner'
`

func (q *Queries) CountClusterOwners(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClusterOwners, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM cluster_members WHERE cluster_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.ClusterID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listMembers = `-- name: ListMembers :many

SELECT m.user_id, u.email, u.display_name, m.role
FROM cluster_members m JOIN users u ON u.id = m.user_id
WHERE m.cluster_id = $1 ORDER BY u.email
`

type ListMembersRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	Role        string    `json:"role"`
}

// Membership 管理（GET/POST/DELETE /api/clusters/{id}/members）查询。
// role 受 cluster_members 的 CHECK 约束（owner/operator/viewer）。
func (q *Queries) ListMembers(ctx context.Context, clusterID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM cluster_members WHERE cluster_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.ClusterID, arg.UserID)
	return err
}

const removeMemberGuarded = `-- name: RemoveMemberGuarded :execrows
DELETE FROM cluster_members AS m
WHERE m.cluster_id = $1 AND m.user_id = $2
  AND (m.role <> 'owner'
       OR (SELECT count(*) FROM cluster_members sub
           WHERE sub.cluster_id = $1 AND sub.role = 'owner') > 1)
`

type RemoveMemberGuardedParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
}

// 原子化的最后 owner 保护：目标非 owner 直接删；是 owner 则须还有其他
// owner（子查询在同一语句内判定，封死查-删分离窗口的并发双删清光 owner）。
// 返回 0 行 = 未删（非成员 或 最后一个 owner），由调用方区分。
func (q *Queries) RemoveMemberGuarded(ctx context.Context, arg RemoveMemberGuardedParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMemberGuarded, arg.ClusterID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMemberRole = `-- name: UpdateMemberRole :execrows
UPDATE cluster_members AS m SET role = $3
WHERE m.cluster_id = $1 AND m.user_id = $2
  AND (m.role <> 'owner' OR $3 = 'owner'
       OR (SELECT count(*) FROM cluster_members sub
           WHERE sub.cluster_id = $1 AND sub.role = 'owner') > 1)
`

type UpdateMemberRoleParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

// 改 role 的同款保护：owner 降级为非 owner 须还有其他 owner。返回 0 行 =
// 未改（非成员 或 最后一个 owner 降级），由调用方区分。
func (q *Queries) UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateMemberRole, arg.ClusterID, arg.UserID, arg.Role)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
