// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID        int64       `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	ClusterID pgtype.UUID `json:"cluster_id"`
	NodeID    pgtype.UUID `json:"node_id"`
	Action    string      `json:"action"`
	SessionID string      `json:"session_id"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
}

type Cluster struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	CreatedAt time.Time          `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	Personal  bool               `json:"personal"`
}

type ClusterMember struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type EnrollmentToken struct {
	ID        uuid.UUID `json:"id"`
	ClusterID uuid.UUID `json:"cluster_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	MaxUses   int32     `json:"max_uses"`
	UsedCount int32     `json:"used_count"`
	CreatedBy uuid.UUID `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
}

type Node struct {
	ID            uuid.UUID          `json:"id"`
	ClusterID     uuid.UUID          `json:"cluster_id"`
	Name          string             `json:"name"`
	MachineID     string             `json:"machine_id"`
	Hostname      string             `json:"hostname"`
	OsVersion     string             `json:"os_version"`
	AgentVersion  string             `json:"agent_version"`
	ShellType     string             `json:"shell_type"`
	PublicKey     string             `json:"public_key"`
	Status        string             `json:"status"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt     time.Time          `json:"created_at"`
	TargetRelease pgtype.Text        `json:"target_release"`
	Channel       string             `json:"channel"`
}

type Relay struct {
	ID          string    `json:"id"`
	Pubkey      string    `json:"pubkey"`
	Region      string    `json:"region"`
	Endpoints   []byte    `json:"endpoints"`
	MaxSessions int32     `json:"max_sessions"`
	MaxMbpsOut  int32     `json:"max_mbps_out"`
	Version     string    `json:"version"`
	Status      string    `json:"status"`
	CreatedAt   time.Time `json:"created_at"`
	LastSeenAt  time.Time `json:"last_seen_at"`
}

type Release struct {
	ID        uuid.UUID `json:"id"`
	Version   string    `json:"version"`
	Notes     string    `json:"notes"`
	CreatedAt time.Time `json:"created_at"`
	Channel   string    `json:"channel"`
}

type ReleaseArtifact struct {
	ID        uuid.UUID `json:"id"`
	ReleaseID uuid.UUID `json:"release_id"`
	Name      string    `json:"name"`
	Sha256    string    `json:"sha256"`
	Size      int64     `json:"size"`
	Data      []byte    `json:"data"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    time.Time          `json:"created_at"`
	IsAdmin      bool               `json:"is_admin"`
	LastLoginAt  pgtype.Timestamptz `json:"last_login_at"`
}
