// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relays.sql

package sqlc

import (
	"context"
)

const getRelay = `-- name: GetRelay :one
SELECT id, pubkey, region, endpoints, max_sessions, max_mbps_out, version, status, created_at, last_seen_at FROM relays WHERE id = $1
`

func (q *Queries) GetRelay(ctx context.Context, id string) (Relay, error) {
	row := q.db.QueryRow(ctx, getRelay, id)
	var i Relay
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Region,
		&i.Endpoints,
		&i.MaxSessions,
		&i.MaxMbpsOut,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getRelayByPubkey = `-- name: GetRelayByPubkey :one
SELECT id, pubkey, region, endpoints, max_sessions, max_mbps_out, version, status, created_at, last_seen_at FROM relays WHERE pubkey = $1
`

func (q *Queries) GetRelayByPubkey(ctx context.Context, pubkey string) (Relay, error) {
	row := q.db.QueryRow(ctx, getRelayByPubkey, pubkey)
	var i Relay
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Region,
		&i.Endpoints,
		&i.MaxSessions,
		&i.MaxMbpsOut,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const listActiveRelays = `-- name: ListActiveRelays :many
SELECT id, pubkey, region, endpoints, max_sessions, max_mbps_out, version, status, created_at, last_seen_at FROM relays WHERE status = 'active' ORDER BY created_at
`

func (q *Queries) ListActiveRelays(ctx context.Context) ([]Relay, error) {
	rows, err := q.db.Query(ctx, listActiveRelays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relay
	for rows.Next() {
		var i Relay
		if err := rows.Scan(
			&i.ID,
			&i.Pubkey,
			&i.Region,
			&i.Endpoints,
			&i.MaxSessions,
			&i.MaxMbpsOut,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRelays = `-- name: ListRelays :many
SELECT id, pubkey, region, endpoints, max_sessions, max_mbps_out, version, status, created_at, last_seen_at FROM relays ORDER BY created_at
`

func (q *Queries) ListRelays(ctx context.Context) ([]Relay, error) {
	rows, err := q.db.Query(ctx, listRelays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Relay
	for rows.Next() {
		var i Relay
		if err := rows.Scan(
			&i.ID,
			&i.Pubkey,
			&i.Region,
			&i.Endpoints,
			&i.MaxSessions,
			&i.MaxMbpsOut,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.LastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRelayStatus = `-- name: SetRelayStatus :execrows
UPDATE relays SET status = $2 WHERE id = $1
`

type SetRelayStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) SetRelayStatus(ctx context.Context, arg SetRelayStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, setRelayStatus, arg.ID, arg.Status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchRelay = `-- name: TouchRelay :exec
UPDATE relays SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchRelay(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchRelay, id)
	return err
}

const upsertRelay = `-- name: UpsertRelay :one
INSERT INTO relays (id, pubkey, region, endpoints, max_sessions, max_mbps_out, version, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (pubkey) DO UPDATE SET
  region = EXCLUDED.region,
  endpoints = EXCLUDED.endpoints,
  max_sessions = EXCLUDED.max_sessions,
  max_mbps_out = EXCLUDED.max_mbps_out,
  version = EXCLUDED.version,
  last_seen_at = now()
RETURNING id, pubkey, region, endpoints, max_sessions, max_mbps_out, version, status, created_at, last_seen_at
`

type UpsertRelayParams struct {
	ID          string `json:"id"`
	Pubkey      string `json:"pubkey"`
	Region      string `json:"region"`
	Endpoints   []byte `json:"endpoints"`
	MaxSessions int32  `json:"max_sessions"`
	MaxMbpsOut  int32  `json:"max_mbps_out"`
	Version     string `json:"version"`
	Status      string `json:"status"`
}

// 注册/再注册：按 pubkey 幂等（relay 重启换 relayId 不换身份）。再注册
// 只刷新画像（endpoints/capacity/version/region）与 last_seen，不触碰
// status——审批语义只归管理端。
func (q *Queries) UpsertRelay(ctx context.Context, arg UpsertRelayParams) (Relay, error) {
	row := q.db.QueryRow(ctx, upsertRelay,
		arg.ID,
		arg.Pubkey,
		arg.Region,
		arg.Endpoints,
		arg.MaxSessions,
		arg.MaxMbpsOut,
		arg.Version,
		arg.Status,
	)
	var i Relay
	err := row.Scan(
		&i.ID,
		&i.Pubkey,
		&i.Region,
		&i.Endpoints,
		&i.MaxSessions,
		&i.MaxMbpsOut,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}
