// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const consumeEnrollmentToken = `-- name: ConsumeEnrollmentToken :one
UPDATE enrollment_tokens SET used_count = used_count + 1
WHERE id = $1 AND used_count < max_uses
RETURNING used_count
`

func (q *Queries) ConsumeEnrollmentToken(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, consumeEnrollmentToken, id)
	var used_count int32
	err := row.Scan(&used_count)
	return used_count, err
}

const createEnrollmentToken = `-- name: CreateEnrollmentToken :one
INSERT INTO enrollment_tokens (id, cluster_id, token_hash, expires_at, max_uses, created_by)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, cluster_id, token_hash, expires_at, max_uses, used_count, created_by, created_at
`

type CreateEnrollmentTokenParams struct {
	ID        uuid.UUID `json:"id"`
	ClusterID uuid.UUID `json:"cluster_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	MaxUses   int32     `json:"max_uses"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateEnrollmentToken(ctx context.Context, arg CreateEnrollmentTokenParams) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, createEnrollmentToken,
		arg.ID,
		arg.ClusterID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.CreatedBy,
	)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getEnrollmentTokenByHash = `-- name: GetEnrollmentTokenByHash :one
SELECT id, cluster_id, token_hash, expires_at, max_uses, used_count, created_by, created_at FROM enrollment_tokens WHERE token_hash = $1
`

func (q *Queries) GetEnrollmentTokenByHash(ctx context.Context, tokenHash string) (EnrollmentToken, error) {
	row := q.db.QueryRow(ctx, getEnrollmentTokenByHash, tokenHash)
	var i EnrollmentToken
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.UsedCount,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
