// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_admin.sql

package sqlc

import (
	"context"
)

const countUsersByEmail = `-- name: CountUsersByEmail :one
SELECT count(*) FROM users WHERE email = $1
`

func (q *Queries) CountUsersByEmail(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByEmail, email)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUserByEmail = `-- name: CreateUserByEmail :one

INSERT INTO users (email, display_name, password_hash)
VALUES ($1, $2, $3) RETURNING id, email, display_name, password_hash, created_at, is_admin
`

type CreateUserByEmailParams struct {
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

// 用户管理（admin-only REST）专用查询。CreateUserByEmail 与既有 CreateUser 的
// 区别：不经调用方生成 id（DB 默认 gen_random_uuid），供 handler 直接消费。
func (q *Queries) CreateUserByEmail(ctx context.Context, arg CreateUserByEmailParams) (User, error) {
	row := q.db.QueryRow(ctx, createUserByEmail, arg.Email, arg.DisplayName, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.IsAdmin,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, display_name, password_hash, created_at, is_admin FROM users ORDER BY email
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.DisplayName,
			&i.PasswordHash,
			&i.CreatedAt,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
