// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_query.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const queryAuditLog = `-- name: QueryAuditLog :many

SELECT id, user_id, cluster_id, node_id, action, session_id, metadata, created_at
FROM audit_logs
WHERE ($1::uuid IS NULL OR node_id = $1)
  AND ($2::uuid IS NULL OR user_id = $2)
  AND ($3::text IS NULL OR action = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
ORDER BY created_at DESC
LIMIT $6 OFFSET $5
`

type QueryAuditLogParams struct {
	NodeID pgtype.UUID        `json:"node_id"`
	UserID pgtype.UUID        `json:"user_id"`
	Action pgtype.Text        `json:"action"`
	Since  pgtype.Timestamptz `json:"since"`
	Offset int32              `json:"offset"`
	Limit  int32              `json:"limit"`
}

// 审计查询（GET /api/audit）：动态 WHERE + 分页。
// sqlc.narg 生成可空参数（pgtype.*）——零值（Valid=false）即 NULL，
// 对应过滤跳过；action/userId/nodeId/since 全部可选组合。
func (q *Queries) QueryAuditLog(ctx context.Context, arg QueryAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, queryAuditLog,
		arg.NodeID,
		arg.UserID,
		arg.Action,
		arg.Since,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClusterID,
			&i.NodeID,
			&i.Action,
			&i.SessionID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
