// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditLog = `-- name: InsertAuditLog :exec
INSERT INTO audit_logs (user_id, cluster_id, node_id, action, metadata)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAuditLogParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ClusterID pgtype.UUID `json:"cluster_id"`
	NodeID    pgtype.UUID `json:"node_id"`
	Action    string      `json:"action"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) InsertAuditLog(ctx context.Context, arg InsertAuditLogParams) error {
	_, err := q.db.Exec(ctx, insertAuditLog,
		arg.UserID,
		arg.ClusterID,
		arg.NodeID,
		arg.Action,
		arg.Metadata,
	)
	return err
}
