// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clusters_admin.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countNodesInCluster = `-- name: CountNodesInCluster :one

SELECT count(*) FROM nodes WHERE cluster_id = $1
`

// Cluster 删除（DELETE /api/clusters/{id}）查询。
// 软删除策略：有节点时端点层拒绝（409），删除即重命名保留审计链。
func (q *Queries) CountNodesInCluster(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countNodesInCluster, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const softDeleteCluster = `-- name: SoftDeleteCluster :exec
UPDATE clusters SET name = $2 WHERE id = $1
`

type SoftDeleteClusterParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) SoftDeleteCluster(ctx context.Context, arg SoftDeleteClusterParams) error {
	_, err := q.db.Exec(ctx, softDeleteCluster, arg.ID, arg.Name)
	return err
}
