// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: membership.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :exec
INSERT INTO cluster_members (cluster_id, user_id, role) VALUES ($1, $2, $3)
`

type AddMemberParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
	Role      string    `json:"role"`
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) error {
	_, err := q.db.Exec(ctx, addMember, arg.ClusterID, arg.UserID, arg.Role)
	return err
}

const countClusterOwners = `-- name: CountClusterOwners :one
SELECT count(*) FROM cluster_members WHERE cluster_id = $1 AND role = 'owner'
`

func (q *Queries) CountClusterOwners(ctx context.Context, clusterID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countClusterOwners, clusterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getMemberRole = `-- name: GetMemberRole :one
SELECT role FROM cluster_members WHERE cluster_id = $1 AND user_id = $2
`

type GetMemberRoleParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) GetMemberRole(ctx context.Context, arg GetMemberRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getMemberRole, arg.ClusterID, arg.UserID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listMembers = `-- name: ListMembers :many

SELECT m.user_id, u.email, u.display_name, m.role
FROM cluster_members m JOIN users u ON u.id = m.user_id
WHERE m.cluster_id = $1 ORDER BY u.email
`

type ListMembersRow struct {
	UserID      uuid.UUID `json:"user_id"`
	Email       string    `json:"email"`
	DisplayName string    `json:"display_name"`
	Role        string    `json:"role"`
}

// Membership 管理（GET/POST/DELETE /api/clusters/{id}/members）查询。
// role 受 cluster_members 的 CHECK 约束（owner/operator/viewer）。
func (q *Queries) ListMembers(ctx context.Context, clusterID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, clusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Email,
			&i.DisplayName,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeMember = `-- name: RemoveMember :exec
DELETE FROM cluster_members WHERE cluster_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	UserID    uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) error {
	_, err := q.db.Exec(ctx, removeMember, arg.ClusterID, arg.UserID)
	return err
}
