// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createNode = `-- name: CreateNode :one
INSERT INTO nodes (id, cluster_id, name, machine_id, hostname, os_version,
                   agent_version, shell_type, public_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) RETURNING id, cluster_id, name, machine_id, hostname, os_version, agent_version, shell_type, public_key, status, last_seen_at, created_at
`

type CreateNodeParams struct {
	ID           uuid.UUID `json:"id"`
	ClusterID    uuid.UUID `json:"cluster_id"`
	Name         string    `json:"name"`
	MachineID    string    `json:"machine_id"`
	Hostname     string    `json:"hostname"`
	OsVersion    string    `json:"os_version"`
	AgentVersion string    `json:"agent_version"`
	ShellType    string    `json:"shell_type"`
	PublicKey    string    `json:"public_key"`
}

func (q *Queries) CreateNode(ctx context.Context, arg CreateNodeParams) (Node, error) {
	row := q.db.QueryRow(ctx, createNode,
		arg.ID,
		arg.ClusterID,
		arg.Name,
		arg.MachineID,
		arg.Hostname,
		arg.OsVersion,
		arg.AgentVersion,
		arg.ShellType,
		arg.PublicKey,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.MachineID,
		&i.Hostname,
		&i.OsVersion,
		&i.AgentVersion,
		&i.ShellType,
		&i.PublicKey,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeByID = `-- name: GetNodeByID :one
SELECT id, cluster_id, name, machine_id, hostname, os_version, agent_version, shell_type, public_key, status, last_seen_at, created_at FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeByID(ctx context.Context, id uuid.UUID) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByID, id)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.MachineID,
		&i.Hostname,
		&i.OsVersion,
		&i.AgentVersion,
		&i.ShellType,
		&i.PublicKey,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeByIdentity = `-- name: GetNodeByIdentity :one
SELECT id, cluster_id, name, machine_id, hostname, os_version, agent_version, shell_type, public_key, status, last_seen_at, created_at FROM nodes WHERE cluster_id = $1 AND machine_id = $2
`

type GetNodeByIdentityParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	MachineID string    `json:"machine_id"`
}

func (q *Queries) GetNodeByIdentity(ctx context.Context, arg GetNodeByIdentityParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByIdentity, arg.ClusterID, arg.MachineID)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.MachineID,
		&i.Hostname,
		&i.OsVersion,
		&i.AgentVersion,
		&i.ShellType,
		&i.PublicKey,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeByNameInCluster = `-- name: GetNodeByNameInCluster :one
SELECT id, cluster_id, name, machine_id, hostname, os_version, agent_version, shell_type, public_key, status, last_seen_at, created_at FROM nodes WHERE cluster_id = $1 AND name = $2
`

type GetNodeByNameInClusterParams struct {
	ClusterID uuid.UUID `json:"cluster_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetNodeByNameInCluster(ctx context.Context, arg GetNodeByNameInClusterParams) (Node, error) {
	row := q.db.QueryRow(ctx, getNodeByNameInCluster, arg.ClusterID, arg.Name)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.MachineID,
		&i.Hostname,
		&i.OsVersion,
		&i.AgentVersion,
		&i.ShellType,
		&i.PublicKey,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}
