// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: nodes_status.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getNodeForUser = `-- name: GetNodeForUser :one
SELECT n.id, n.cluster_id, n.name, n.hostname, n.os_version, n.agent_version,
       n.shell_type, n.status, n.last_seen_at, c.name AS cluster_name
FROM nodes n
JOIN cluster_members m ON m.cluster_id = n.cluster_id AND m.user_id = $1
JOIN clusters c ON c.id = n.cluster_id
WHERE n.id = $2
`

type GetNodeForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	ID     uuid.UUID `json:"id"`
}

type GetNodeForUserRow struct {
	ID           uuid.UUID          `json:"id"`
	ClusterID    uuid.UUID          `json:"cluster_id"`
	Name         string             `json:"name"`
	Hostname     string             `json:"hostname"`
	OsVersion    string             `json:"os_version"`
	AgentVersion string             `json:"agent_version"`
	ShellType    string             `json:"shell_type"`
	Status       string             `json:"status"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	ClusterName  string             `json:"cluster_name"`
}

func (q *Queries) GetNodeForUser(ctx context.Context, arg GetNodeForUserParams) (GetNodeForUserRow, error) {
	row := q.db.QueryRow(ctx, getNodeForUser, arg.UserID, arg.ID)
	var i GetNodeForUserRow
	err := row.Scan(
		&i.ID,
		&i.ClusterID,
		&i.Name,
		&i.Hostname,
		&i.OsVersion,
		&i.AgentVersion,
		&i.ShellType,
		&i.Status,
		&i.LastSeenAt,
		&i.ClusterName,
	)
	return i, err
}

const listNodesForUser = `-- name: ListNodesForUser :many
SELECT n.id, n.cluster_id, n.name, n.hostname, n.os_version, n.agent_version,
       n.shell_type, n.status, n.last_seen_at, c.name AS cluster_name
FROM nodes n
JOIN cluster_members m ON m.cluster_id = n.cluster_id AND m.user_id = $1
JOIN clusters c ON c.id = n.cluster_id
ORDER BY c.name, n.name
`

type ListNodesForUserRow struct {
	ID           uuid.UUID          `json:"id"`
	ClusterID    uuid.UUID          `json:"cluster_id"`
	Name         string             `json:"name"`
	Hostname     string             `json:"hostname"`
	OsVersion    string             `json:"os_version"`
	AgentVersion string             `json:"agent_version"`
	ShellType    string             `json:"shell_type"`
	Status       string             `json:"status"`
	LastSeenAt   pgtype.Timestamptz `json:"last_seen_at"`
	ClusterName  string             `json:"cluster_name"`
}

func (q *Queries) ListNodesForUser(ctx context.Context, userID uuid.UUID) ([]ListNodesForUserRow, error) {
	rows, err := q.db.Query(ctx, listNodesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodesForUserRow
	for rows.Next() {
		var i ListNodesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ClusterID,
			&i.Name,
			&i.Hostname,
			&i.OsVersion,
			&i.AgentVersion,
			&i.ShellType,
			&i.Status,
			&i.LastSeenAt,
			&i.ClusterName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNodeStatus = `-- name: SetNodeStatus :exec
UPDATE nodes SET status = $2 WHERE id = $1
`

type SetNodeStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) SetNodeStatus(ctx context.Context, arg SetNodeStatusParams) error {
	_, err := q.db.Exec(ctx, setNodeStatus, arg.ID, arg.Status)
	return err
}

const touchNode = `-- name: TouchNode :exec
UPDATE nodes SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchNode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchNode, id)
	return err
}

const updateNodeMeta = `-- name: UpdateNodeMeta :exec
UPDATE nodes SET hostname = $1, shell_type = $2, agent_version = $3
WHERE id = $4
`

type UpdateNodeMetaParams struct {
	Hostname     string    `json:"hostname"`
	ShellType    string    `json:"shell_type"`
	AgentVersion string    `json:"agent_version"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateNodeMeta(ctx context.Context, arg UpdateNodeMetaParams) error {
	_, err := q.db.Exec(ctx, updateNodeMeta,
		arg.Hostname,
		arg.ShellType,
		arg.AgentVersion,
		arg.ID,
	)
	return err
}
