// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (version, notes, channel) VALUES ($1, $2, $3)
ON CONFLICT (version) DO UPDATE SET notes = EXCLUDED.notes, channel = EXCLUDED.channel
RETURNING id, version, notes, created_at, channel
`

type CreateReleaseParams struct {
	Version string `json:"version"`
	Notes   string `json:"notes"`
	Channel string `json:"channel"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, createRelease, arg.Version, arg.Notes, arg.Channel)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Notes,
		&i.CreatedAt,
		&i.Channel,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, release_id, name, sha256, size, data, created_at FROM release_artifacts WHERE release_id = $1 AND name = $2
`

type GetArtifactParams struct {
	ReleaseID uuid.UUID `json:"release_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (ReleaseArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.ReleaseID, arg.Name)
	var i ReleaseArtifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Name,
		&i.Sha256,
		&i.Size,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestReleaseByChannel = `-- name: GetLatestReleaseByChannel :one
SELECT id, version, notes, created_at, channel FROM releases WHERE channel = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestReleaseByChannel(ctx context.Context, channel string) (Release, error) {
	row := q.db.QueryRow(ctx, getLatestReleaseByChannel, channel)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Notes,
		&i.CreatedAt,
		&i.Channel,
	)
	return i, err
}

const getNodeTargetRelease = `-- name: GetNodeTargetRelease :one
SELECT target_release, channel FROM nodes WHERE id = $1
`

type GetNodeTargetReleaseRow struct {
	TargetRelease pgtype.Text `json:"target_release"`
	Channel       string      `json:"channel"`
}

func (q *Queries) GetNodeTargetRelease(ctx context.Context, id uuid.UUID) (GetNodeTargetReleaseRow, error) {
	row := q.db.QueryRow(ctx, getNodeTargetRelease, id)
	var i GetNodeTargetReleaseRow
	err := row.Scan(&i.TargetRelease, &i.Channel)
	return i, err
}

const getReleaseByVersion = `-- name: GetReleaseByVersion :one
SELECT id, version, notes, created_at, channel FROM releases WHERE version = $1
`

func (q *Queries) GetReleaseByVersion(ctx context.Context, version string) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByVersion, version)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Notes,
		&i.CreatedAt,
		&i.Channel,
	)
	return i, err
}

const listReleases = `-- name: ListReleases :many
SELECT id, version, notes, channel, created_at FROM releases ORDER BY created_at DESC LIMIT 50
`

type ListReleasesRow struct {
	ID        uuid.UUID `json:"id"`
	Version   string    `json:"version"`
	Notes     string    `json:"notes"`
	Channel   string    `json:"channel"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) ListReleases(ctx context.Context) ([]ListReleasesRow, error) {
	rows, err := q.db.Query(ctx, listReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReleasesRow
	for rows.Next() {
		var i ListReleasesRow
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Notes,
			&i.Channel,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putArtifact = `-- name: PutArtifact :exec
INSERT INTO release_artifacts (release_id, name, sha256, size, data)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (release_id, name) DO UPDATE
SET sha256 = EXCLUDED.sha256, size = EXCLUDED.size, data = EXCLUDED.data
`

type PutArtifactParams struct {
	ReleaseID uuid.UUID `json:"release_id"`
	Name      string    `json:"name"`
	Sha256    string    `json:"sha256"`
	Size      int64     `json:"size"`
	Data      []byte    `json:"data"`
}

func (q *Queries) PutArtifact(ctx context.Context, arg PutArtifactParams) error {
	_, err := q.db.Exec(ctx, putArtifact,
		arg.ReleaseID,
		arg.Name,
		arg.Sha256,
		arg.Size,
		arg.Data,
	)
	return err
}

const setNodeChannel = `-- name: SetNodeChannel :exec
UPDATE nodes SET channel = $2 WHERE id = $1
`

type SetNodeChannelParams struct {
	ID      uuid.UUID `json:"id"`
	Channel string    `json:"channel"`
}

func (q *Queries) SetNodeChannel(ctx context.Context, arg SetNodeChannelParams) error {
	_, err := q.db.Exec(ctx, setNodeChannel, arg.ID, arg.Channel)
	return err
}

const setNodeTargetRelease = `-- name: SetNodeTargetRelease :exec
UPDATE nodes SET target_release = $2 WHERE id = $1
`

type SetNodeTargetReleaseParams struct {
	ID            uuid.UUID   `json:"id"`
	TargetRelease pgtype.Text `json:"target_release"`
}

func (q *Queries) SetNodeTargetRelease(ctx context.Context, arg SetNodeTargetReleaseParams) error {
	_, err := q.db.Exec(ctx, setNodeTargetRelease, arg.ID, arg.TargetRelease)
	return err
}
