// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (version, notes) VALUES ($1, $2)
ON CONFLICT (version) DO UPDATE SET notes = EXCLUDED.notes
RETURNING id, version, notes, created_at
`

type CreateReleaseParams struct {
	Version string `json:"version"`
	Notes   string `json:"notes"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, createRelease, arg.Version, arg.Notes)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getArtifact = `-- name: GetArtifact :one
SELECT id, release_id, name, sha256, size, data, created_at FROM release_artifacts WHERE release_id = $1 AND name = $2
`

type GetArtifactParams struct {
	ReleaseID uuid.UUID `json:"release_id"`
	Name      string    `json:"name"`
}

func (q *Queries) GetArtifact(ctx context.Context, arg GetArtifactParams) (ReleaseArtifact, error) {
	row := q.db.QueryRow(ctx, getArtifact, arg.ReleaseID, arg.Name)
	var i ReleaseArtifact
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Name,
		&i.Sha256,
		&i.Size,
		&i.Data,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestRelease = `-- name: GetLatestRelease :one
SELECT id, version, notes, created_at FROM releases ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestRelease(ctx context.Context) (Release, error) {
	row := q.db.QueryRow(ctx, getLatestRelease)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getNodeTargetRelease = `-- name: GetNodeTargetRelease :one
SELECT target_release FROM nodes WHERE id = $1
`

func (q *Queries) GetNodeTargetRelease(ctx context.Context, id uuid.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getNodeTargetRelease, id)
	var target_release pgtype.Text
	err := row.Scan(&target_release)
	return target_release, err
}

const getReleaseByVersion = `-- name: GetReleaseByVersion :one
SELECT id, version, notes, created_at FROM releases WHERE version = $1
`

func (q *Queries) GetReleaseByVersion(ctx context.Context, version string) (Release, error) {
	row := q.db.QueryRow(ctx, getReleaseByVersion, version)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Version,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const listReleases = `-- name: ListReleases :many
SELECT id, version, notes, created_at FROM releases ORDER BY created_at DESC LIMIT 50
`

func (q *Queries) ListReleases(ctx context.Context) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.Version,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const putArtifact = `-- name: PutArtifact :exec
INSERT INTO release_artifacts (release_id, name, sha256, size, data)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (release_id, name) DO UPDATE
SET sha256 = EXCLUDED.sha256, size = EXCLUDED.size, data = EXCLUDED.data
`

type PutArtifactParams struct {
	ReleaseID uuid.UUID `json:"release_id"`
	Name      string    `json:"name"`
	Sha256    string    `json:"sha256"`
	Size      int64     `json:"size"`
	Data      []byte    `json:"data"`
}

func (q *Queries) PutArtifact(ctx context.Context, arg PutArtifactParams) error {
	_, err := q.db.Exec(ctx, putArtifact,
		arg.ReleaseID,
		arg.Name,
		arg.Sha256,
		arg.Size,
		arg.Data,
	)
	return err
}

const setNodeTargetRelease = `-- name: SetNodeTargetRelease :exec
UPDATE nodes SET target_release = $2 WHERE id = $1
`

type SetNodeTargetReleaseParams struct {
	ID            uuid.UUID   `json:"id"`
	TargetRelease pgtype.Text `json:"target_release"`
}

func (q *Queries) SetNodeTargetRelease(ctx context.Context, arg SetNodeTargetReleaseParams) error {
	_, err := q.db.Exec(ctx, setNodeTargetRelease, arg.ID, arg.TargetRelease)
	return err
}
